from __future__ import annotations
# ruff: noqa: E402

import argparse
import os
import shutil
import subprocess
from pathlib import Path
import sys


REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from runtime_config import (
    resolve_policyengine_us_path,
    resolve_projected_datasets_path,
    resolve_projected_datasets_snapshot_path,
)
from repro_bundle import create_repro_bundle, resolved_environment_contract, snapshot_summary


DEFAULT_POLICYENGINE_US_PATH = resolve_policyengine_us_path()
DEFAULT_PROJECTED_DATASETS_PATH = resolve_projected_datasets_path()
DEFAULT_SNAPSHOT_PATH = resolve_projected_datasets_snapshot_path()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Snapshot local calibrated H5 datasets and launch the Modal rerun."
    )
    parser.add_argument("--reforms", required=True, help="Comma-separated reform IDs.")
    parser.add_argument(
        "--scoring",
        default="static",
        choices=["static", "dynamic"],
        help="Scoring mode to run on Modal.",
    )
    parser.add_argument(
        "--years",
        required=True,
        help="Year range like 2026-2030 or a comma-separated list.",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output CSV path passed through to modal_batch/compute.py::run_reforms.",
    )
    parser.add_argument(
        "--policyengine-us-path",
        type=Path,
        default=DEFAULT_POLICYENGINE_US_PATH,
        help="Local policyengine-us checkout/worktree to package into Modal.",
    )
    parser.add_argument(
        "--projected-datasets-path",
        type=Path,
        default=DEFAULT_PROJECTED_DATASETS_PATH,
        help="Live projected_datasets directory generated by policyengine-us-data.",
    )
    parser.add_argument(
        "--snapshot-path",
        type=Path,
        default=DEFAULT_SNAPSHOT_PATH,
        help="Stable snapshot directory copied into the Modal image.",
    )
    parser.add_argument(
        "--detach",
        action="store_true",
        help="Launch the Modal run in detached mode so it survives client disconnects.",
    )
    parser.add_argument(
        "--modal-target",
        default="run_reforms",
        choices=["run_reforms", "run_cells", "submit_cells"],
        help="Which modal_batch/compute.py entrypoint to run.",
    )
    parser.add_argument(
        "--repro-bundle-root",
        type=Path,
        default=REPO_ROOT / "results" / "repro_bundles",
        help="Directory where run-level reproducibility bundles are written.",
    )
    return parser.parse_args()


def sync_snapshot(source: Path, snapshot: Path) -> None:
    if not source.exists():
        raise FileNotFoundError(f"Projected datasets path not found: {source}")

    snapshot.mkdir(parents=True, exist_ok=True)

    source_files = {path.name: path for path in source.glob("*.h5")}
    snapshot_files = {path.name: path for path in snapshot.glob("*.h5")}

    for stale_name, stale_path in snapshot_files.items():
        if stale_name not in source_files:
            stale_path.unlink()
            stale_metadata = snapshot / f"{stale_name}.metadata.json"
            if stale_metadata.exists():
                stale_metadata.unlink()

    for name, source_path in sorted(source_files.items()):
        target_path = snapshot / name
        if not target_path.exists() or source_path.stat().st_mtime > target_path.stat().st_mtime:
            shutil.copy2(source_path, target_path)
            print(f"Snapshotted {name}")

        source_metadata = source / f"{name}.metadata.json"
        target_metadata = snapshot / f"{name}.metadata.json"
        if source_metadata.exists():
            if (
                not target_metadata.exists()
                or source_metadata.stat().st_mtime > target_metadata.stat().st_mtime
            ):
                shutil.copy2(source_metadata, target_metadata)
                print(f"Snapshotted {source_metadata.name}")
        elif target_metadata.exists():
            target_metadata.unlink()

    source_manifest = source / "calibration_manifest.json"
    target_manifest = snapshot / "calibration_manifest.json"
    if source_manifest.exists():
        if (
            not target_manifest.exists()
            or source_manifest.stat().st_mtime > target_manifest.stat().st_mtime
        ):
            shutil.copy2(source_manifest, target_manifest)
            print("Snapshotted calibration_manifest.json")
    elif target_manifest.exists():
        target_manifest.unlink()


def launch_modal(args: argparse.Namespace) -> int:
    env = os.environ.copy()
    snapshot_info = snapshot_summary(args.snapshot_path)
    contract_env = resolved_environment_contract(
        policyengine_us_path=args.policyengine_us_path,
        projected_datasets_path=args.snapshot_path,
        snapshot_path=args.snapshot_path,
        environ=env,
        snapshot_info=snapshot_info,
    )
    for key, value in contract_env.items():
        if value is not None:
            env[key] = value

    command = [
        "uvx",
        "--from",
        "modal",
        "--with",
        "pandas",
        "modal",
        "run",
    ]

    if args.detach:
        command.append("--detach")

    command.extend(
        [
        str(REPO_ROOT / f"modal_batch/compute.py::{args.modal_target}"),
        "--reforms",
        args.reforms,
        "--scoring",
        args.scoring,
        "--years",
        args.years,
        "--output",
        args.output,
        ]
    )

    print(f"Launching: {' '.join(command)}")
    completed = subprocess.run(command, cwd=REPO_ROOT, env=env)
    return completed.returncode


def main() -> int:
    args = parse_args()
    sync_snapshot(args.projected_datasets_path, args.snapshot_path)
    print(f"Snapshot ready at {args.snapshot_path}")
    bundle = create_repro_bundle(
        repo_root=REPO_ROOT,
        output_path=Path(args.output),
        scoring=args.scoring,
        reforms=args.reforms,
        years=args.years,
        modal_target=args.modal_target,
        policyengine_us_path=args.policyengine_us_path,
        projected_datasets_path=args.projected_datasets_path,
        snapshot_path=args.snapshot_path,
        bundle_root=args.repro_bundle_root,
    )
    print(f"Reproducibility bundle: {bundle.bundle_dir}")
    print(f"Run manifest: {bundle.manifest_path}")
    return launch_modal(args)


if __name__ == "__main__":
    raise SystemExit(main())
