from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, UTC
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import time

from modal_run_protocol import (
    build_cells,
    build_run_id,
    parse_reforms,
    parse_years,
    run_paths,
)
from modal_cli import modal_cli_prefix, modal_python_prefix, modal_subprocess_env
from projected_dataset_snapshot import (
    prepare_snapshot_path,
    sync_projected_dataset_snapshot,
)
from runtime_config import (
    resolve_policyengine_us_path,
    resolve_projected_datasets_path,
    validate_dataset_contract,
)
from tax_assumption_loader import (
    DEFAULT_TAX_ASSUMPTION_FACTORY,
    resolve_tax_assumption_module,
)


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_ROOT = REPO_ROOT / "results" / "modal_runs"
DEFAULT_REQUIRED_PROFILE = "ss-payroll-tob"
DEFAULT_REQUIRED_TARGET_SOURCE = "oact_2025_08_05_provisional"
DEFAULT_REQUIRED_TAX_ASSUMPTION = "trustees-core-thresholds-v1"
DEFAULT_MIN_CALIBRATION_QUALITY = "exact"
DEPLOYED_MODAL_APP_NAME = "crfb-ss-analysis"
MODAL_WORKER_TARGETS = {
    "large": "materialize_scenario_from_run",
    "medium": "materialize_scenario_from_run_medium",
    "small": "materialize_scenario_from_run_small",
}
MODAL_WORKER_RESOURCES = {
    "large": {"cpu": 4, "memory_mb": 65536},
    "medium": {"cpu": 4, "memory_mb": 32768},
    "small": {"cpu": 2, "memory_mb": 16384},
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Submit a fully remote Modal run with one job per year-scenario "
            "and remote manifest/status artifacts."
        )
    )
    parser.add_argument("--reforms", required=True, help="Comma-separated reform IDs.")
    parser.add_argument("--years", required=True, help="Year range or list.")
    parser.add_argument(
        "--scoring",
        default="static",
        choices=["static", "dynamic"],
        help="CRFB scoring type.",
    )
    parser.add_argument(
        "--label",
        default="modal-scenarios",
        help="Human-readable run label used in run_id construction.",
    )
    parser.add_argument(
        "--output-root",
        default=str(DEFAULT_OUTPUT_ROOT),
        help="Local directory for manifest mirrors and recovered runs.",
    )
    parser.add_argument(
        "--include-baseline",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Include the baseline scenario for each year.",
    )
    parser.add_argument(
        "--policyengine-us-path",
        type=Path,
        default=resolve_policyengine_us_path(),
        help="Local policyengine-us checkout/worktree to package into Modal.",
    )
    parser.add_argument(
        "--projected-datasets-path",
        type=Path,
        default=resolve_projected_datasets_path(),
        help="Live projected_datasets directory generated by policyengine-us-data.",
    )
    parser.add_argument(
        "--snapshot-path",
        type=Path,
        default=None,
        help=(
            "Stable snapshot directory copied into the Modal image. If omitted, "
            "a fresh immutable per-run snapshot is created under "
            "projected_datasets_snapshots/."
        ),
    )
    parser.add_argument(
        "--tax-assumption-module",
        help="Path to the long-run tax assumption module.",
    )
    parser.add_argument(
        "--tax-assumption-factory",
        default=DEFAULT_TAX_ASSUMPTION_FACTORY,
        help="Factory function name inside --tax-assumption-module.",
    )
    parser.add_argument(
        "--tax-assumption-start-year",
        type=int,
        default=2035,
        help="Start year for the tax assumption factory.",
    )
    parser.add_argument(
        "--tax-assumption-end-year",
        type=int,
        default=2100,
        help="End year for the tax assumption factory.",
    )
    parser.add_argument(
        "--required-profile",
        default=DEFAULT_REQUIRED_PROFILE,
        help="Expected calibration profile name in H5 metadata.",
    )
    parser.add_argument(
        "--required-target-source",
        default=DEFAULT_REQUIRED_TARGET_SOURCE,
        help="Expected target source name in H5 metadata.",
    )
    parser.add_argument(
        "--required-tax-assumption",
        default=DEFAULT_REQUIRED_TAX_ASSUMPTION,
        help="Expected tax assumption name in H5 metadata.",
    )
    parser.add_argument(
        "--minimum-calibration-quality",
        default=DEFAULT_MIN_CALIBRATION_QUALITY,
        choices=["aggregate", "approximate", "exact"],
        help="Minimum calibration quality required in H5 metadata.",
    )
    parser.add_argument(
        "--launch-jobs",
        type=int,
        default=0,
        help=(
            "Concurrent detached launch workers. Use 0 to launch all cells in "
            "parallel."
        ),
    )
    parser.add_argument(
        "--modal-worker-profile",
        default="large",
        choices=sorted(MODAL_WORKER_TARGETS),
        help="Modal worker size to use for each scenario materialization.",
    )
    return parser.parse_args()


def _sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _git_head(path: Path) -> str | None:
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=path,
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return None
    return result.stdout.strip()


def _git_dirty(path: Path) -> bool | None:
    result = subprocess.run(
        ["git", "status", "--porcelain=v1"],
        cwd=path,
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return None
    return bool(result.stdout.strip())


def dataset_spec(
    *,
    year: int,
    dataset_path: Path,
    required_profile: str,
    minimum_calibration_quality: str,
    required_target_source: str,
    required_tax_assumption: str,
) -> dict:
    metadata = validate_dataset_contract(
        dataset_path,
        required_profile=required_profile,
        minimum_calibration_quality=minimum_calibration_quality,
        required_target_source=required_target_source,
        required_tax_assumption=required_tax_assumption,
        reject_aggregate=False,
        allow_unvalidated=False,
    )
    metadata_path = Path(f"{dataset_path}.metadata.json")
    stat = dataset_path.stat()
    return {
        "year": year,
        "local_path": str(dataset_path),
        "metadata_path": str(metadata_path),
        "dataset_size": stat.st_size,
        "dataset_mtime_ns": stat.st_mtime_ns,
        "metadata_sha256": _sha256_file(metadata_path),
        "metadata": metadata,
    }


def build_run_spec(args: argparse.Namespace) -> tuple[dict, Path]:
    if not args.include_baseline:
        raise ValueError(
            "Manifest-driven scenario runs currently require baseline cells. "
            "Use --include-baseline."
        )

    reforms = parse_reforms(args.reforms)
    years = parse_years(args.years)
    if args.snapshot_path is None:
        raise ValueError("snapshot_path must be prepared before build_run_spec")
    snapshot_path = args.snapshot_path
    tax_assumption_module = resolve_tax_assumption_module(args.tax_assumption_module)

    datasets = {
        str(year): dataset_spec(
            year=year,
            dataset_path=snapshot_path / f"{year}.h5",
            required_profile=args.required_profile,
            minimum_calibration_quality=args.minimum_calibration_quality,
            required_target_source=args.required_target_source,
            required_tax_assumption=args.required_tax_assumption,
        )
        for year in years
    }

    payload = {
        "label": args.label,
        "scoring": args.scoring,
        "include_baseline": args.include_baseline,
        "reforms": reforms,
        "years": years,
        "cells": build_cells(
            years=years,
            reforms=reforms,
            include_baseline=args.include_baseline,
        ),
        "tax_assumption": {
            "module_local_path": str(tax_assumption_module),
            "module_sha256": _sha256_file(tax_assumption_module),
            "factory": args.tax_assumption_factory,
            "start_year": args.tax_assumption_start_year,
            "end_year": args.tax_assumption_end_year,
        },
        "datasets": datasets,
        "dataset_contract": {
            "required_profile": args.required_profile,
            "minimum_calibration_quality": args.minimum_calibration_quality,
            "required_target_source": args.required_target_source,
            "required_tax_assumption": args.required_tax_assumption,
        },
        "provenance": {
            "created_at": datetime.now(UTC).isoformat(),
            "crfb_repo": {
                "path": str(REPO_ROOT),
                "git_head": _git_head(REPO_ROOT),
                "git_dirty": _git_dirty(REPO_ROOT),
            },
            "policyengine_us": {
                "path": str(args.policyengine_us_path),
                "git_head": _git_head(args.policyengine_us_path),
                "git_dirty": _git_dirty(args.policyengine_us_path),
            },
            "projected_datasets_snapshot_path": str(snapshot_path),
        },
        "execution": {
            "modal_worker_profile": args.modal_worker_profile,
            **MODAL_WORKER_RESOURCES[args.modal_worker_profile],
        },
    }

    run_id = build_run_id(args.label, payload)
    spec = {
        **payload,
        "run_id": run_id,
        "created_at": datetime.now(UTC).isoformat(),
    }
    run_dir = Path(args.output_root).expanduser().resolve() / run_id
    return spec, run_dir


def modal_volume(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [*modal_cli_prefix(), "volume", *args],
        cwd=REPO_ROOT,
        env=modal_subprocess_env(),
        capture_output=True,
        text=True,
        check=False,
    )


def upload_volume_file(local_path: Path, remote_path: Path) -> None:
    max_attempts = 6
    for attempt in range(1, max_attempts + 1):
        completed = modal_volume(
            "put",
            "--force",
            "crfb-results",
            str(local_path),
            str(remote_path),
        )
        if completed.returncode == 0:
            return
        stderr = completed.stderr or ""
        retryable = (
            "rate limit exceeded" in stderr.lower()
            or "too many layers" in stderr.lower()
        )
        if not retryable or attempt == max_attempts:
            raise RuntimeError(
                "modal volume put failed for "
                f"{local_path} -> {remote_path}:\n{stderr}"
            )
        time.sleep(min(2**attempt, 15))


def upload_json(payload: dict, remote_path: Path) -> None:
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        suffix=".json",
        delete=False,
    ) as temp_file:
        temp_path = Path(temp_file.name)
        temp_file.write(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    try:
        upload_volume_file(temp_path, remote_path)
    finally:
        temp_path.unlink(missing_ok=True)


def upload_run_manifest(spec_path: Path, spec: dict) -> None:
    paths = run_paths(spec["run_id"])
    upload_volume_file(spec_path, paths.manifest)
    upload_json(
        {
            "run_id": spec["run_id"],
            "submitted_at": datetime.now(UTC).isoformat(),
            "expected_cells": len(spec.get("cells", [])),
        },
        paths.root / "submitted.json",
    )


def modal_worker_target(profile: str) -> str:
    return MODAL_WORKER_TARGETS[profile]


def build_modal_deploy_command() -> list[str]:
    return [
        *modal_cli_prefix(),
        "deploy",
        str(REPO_ROOT / "modal_batch/compute.py"),
        "--no-stream-logs",
    ]


def build_modal_probe_command(*, worker_profile: str) -> list[str]:
    return [
        *modal_python_prefix(),
        str(REPO_ROOT / "src" / "modal_check_deployed_function.py"),
        "--app-name",
        DEPLOYED_MODAL_APP_NAME,
        "--function-name",
        modal_worker_target(worker_profile),
    ]


def build_modal_spawn_command(cell: dict, *, worker_profile: str) -> list[str]:
    command = [
        *modal_python_prefix(),
        str(REPO_ROOT / "src" / "modal_spawn_deployed_call.py"),
        "--app-name",
        DEPLOYED_MODAL_APP_NAME,
        "--function-name",
        modal_worker_target(worker_profile),
        "--run-id",
        str(cell["run_id"]),
        "--year",
        str(cell["year"]),
        "--scenario-name",
        str(cell["scenario_name"]),
    ]
    reform_id = cell.get("reform_id")
    if reform_id:
        command.extend(["--reform-id", str(reform_id)])
    return command


def build_submitted_record(
    cell: dict,
    call_id: str,
    dashboard_url: str,
    launched_at: str,
    *,
    startup_confirmed: bool,
    function_name: str,
) -> dict:
    return {
        "year": int(cell["year"]),
        "scenario_name": str(cell["scenario_name"]),
        "reform_id": cell.get("reform_id"),
        "launched_at": launched_at,
        "call_id": call_id,
        "dashboard_url": dashboard_url,
        "function_name": function_name,
        "submission_mode": "deployed_function_spawn",
        "startup_confirmed": startup_confirmed,
    }


def build_launch_failure_record(cell: dict, launched_at: str, error: Exception) -> dict:
    return {
        "year": int(cell["year"]),
        "scenario_name": str(cell["scenario_name"]),
        "reform_id": cell.get("reform_id"),
        "launched_at": launched_at,
        "error": f"{type(error).__name__}: {error}",
    }


def parse_spawn_record(output: str) -> dict | None:
    for line in reversed(output.splitlines()):
        candidate = line.strip()
        if not candidate:
            continue
        try:
            payload = json.loads(candidate)
        except json.JSONDecodeError:
            continue
        if isinstance(payload, dict) and payload.get("call_id"):
            return payload
    return None


def launch_spawned_modal_call(
    command: list[str],
    env: dict[str, str],
) -> dict:
    completed = subprocess.run(
        command,
        cwd=REPO_ROOT,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    output = "\n".join(
        part.strip()
        for part in (completed.stdout, completed.stderr)
        if part and part.strip()
    )
    if completed.returncode != 0:
        raise RuntimeError(output or "Modal spawn helper failed")
    record = parse_spawn_record(output)
    if record is None:
        raise RuntimeError(output or "Modal spawn helper did not emit call metadata")
    return record


def deployed_function_ready(env: dict[str, str], *, worker_profile: str) -> bool:
    completed = subprocess.run(
        build_modal_probe_command(worker_profile=worker_profile),
        cwd=REPO_ROOT,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )
    return completed.returncode == 0


def _terminate_process(process: subprocess.Popen[str]) -> None:
    if process.poll() is not None:
        return
    process.terminate()
    try:
        process.wait(timeout=5)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait(timeout=5)


def _read_process_output(process: subprocess.Popen[str]) -> str:
    stdout = ""
    stderr = ""
    if process.stdout is not None:
        stdout = process.stdout.read()
    if process.stderr is not None:
        stderr = process.stderr.read()
    return "\n".join(part.strip() for part in (stdout, stderr) if part and part.strip())


def ensure_deployed_modal_app(
    env: dict[str, str],
    *,
    worker_profile: str,
    wait_timeout_seconds: float = 300.0,
    probe_interval_seconds: float = 5.0,
) -> None:
    process = subprocess.Popen(
        build_modal_deploy_command(),
        cwd=REPO_ROOT,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    deadline = time.monotonic() + wait_timeout_seconds
    while time.monotonic() < deadline:
        if process.poll() is not None:
            if process.returncode == 0:
                return
            if deployed_function_ready(env, worker_profile=worker_profile):
                return
            output = _read_process_output(process)
            raise RuntimeError(output or "modal deploy failed")
        if deployed_function_ready(env, worker_profile=worker_profile):
            _terminate_process(process)
            return
        time.sleep(probe_interval_seconds)

    if deployed_function_ready(env, worker_profile=worker_profile):
        _terminate_process(process)
        return

    _terminate_process(process)
    output = _read_process_output(process)
    raise RuntimeError(output or "Timed out waiting for deployed Modal app")


def effective_launch_jobs(args: argparse.Namespace, *, cell_count: int) -> int:
    if cell_count <= 0:
        return 1
    if args.launch_jobs <= 0:
        return cell_count
    return min(args.launch_jobs, cell_count)


def launch_cell(
    *,
    spec: dict,
    raw_cell: dict,
    env: dict[str, str],
    worker_profile: str,
    index: int,
    total: int,
) -> tuple[int, dict | None, dict | None]:
    cell = {
        **raw_cell,
        "run_id": spec["run_id"],
    }
    print(
        f"[{index}/{total}] Launching "
        f"year={cell['year']} scenario={cell['scenario_name']}"
    )
    launched_at = datetime.now(UTC).isoformat()
    try:
        function_name = modal_worker_target(worker_profile)
        spawn_record = launch_spawned_modal_call(
            build_modal_spawn_command(cell, worker_profile=worker_profile),
            env,
        )
        record = build_submitted_record(
            cell,
            str(spawn_record["call_id"]),
            str(spawn_record.get("dashboard_url") or ""),
            launched_at,
            startup_confirmed=False,
            function_name=function_name,
        )
        return index, record, None
    except Exception as error:
        failure = build_launch_failure_record(cell, launched_at, error)
        print(
            f"Launch failed for year={cell['year']} "
            f"scenario={cell['scenario_name']}: {error}",
            file=sys.stderr,
        )
        return index, None, failure


def launch(spec_path: Path, spec: dict, args: argparse.Namespace) -> int:
    os.environ["CRFB_POLICYENGINE_US_PATH"] = str(args.policyengine_us_path)
    os.environ["CRFB_PROJECTED_DATASETS_PATH"] = str(args.snapshot_path)
    os.environ["CRFB_PROJECTED_DATASETS_SNAPSHOT_PATH"] = str(args.snapshot_path)
    os.environ["CRFB_TAX_ASSUMPTION_MODULE"] = str(
        resolve_tax_assumption_module(args.tax_assumption_module)
    )
    upload_run_manifest(spec_path, spec)

    dispatch_records: list[dict] = []
    launch_failures: list[dict] = []
    env = modal_subprocess_env(os.environ.copy())
    print(f"Deploying Modal app {DEPLOYED_MODAL_APP_NAME}...")
    ensure_deployed_modal_app(env, worker_profile=args.modal_worker_profile)
    total = len(spec["cells"])
    launch_jobs = effective_launch_jobs(args, cell_count=total)
    results_by_index: dict[int, tuple[dict | None, dict | None]] = {}
    with ThreadPoolExecutor(max_workers=launch_jobs) as executor:
        futures = [
            executor.submit(
                launch_cell,
                spec=spec,
                raw_cell=raw_cell,
                env=env,
                worker_profile=args.modal_worker_profile,
                index=index,
                total=total,
            )
            for index, raw_cell in enumerate(spec["cells"], start=1)
        ]
        for future in as_completed(futures):
            index, record, failure = future.result()
            results_by_index[index] = (record, failure)

    for index in sorted(results_by_index):
        record, failure = results_by_index[index]
        if record is not None:
            dispatch_records.append(record)
        if failure is not None:
            launch_failures.append(failure)

    dispatch_payload = {
        "run_id": spec["run_id"],
        "dispatched_at": datetime.now(UTC).isoformat(),
        "expected_cells": len(spec["cells"]),
        "submitted_cells": len(dispatch_records),
        "failed_launches": len(launch_failures),
        "submitted": [record for record in dispatch_records],
        "failed": launch_failures,
    }
    upload_json(dispatch_payload, run_paths(spec["run_id"]).root / "dispatch.json")

    local_dispatch_path = spec_path.parent / "dispatch.json"
    local_dispatch_path.write_text(
        json.dumps(dispatch_payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return 0 if not launch_failures else 1


def main() -> int:
    args = parse_args()
    args.snapshot_path = prepare_snapshot_path(
        args.projected_datasets_path,
        args.snapshot_path,
        repo_root=REPO_ROOT,
        label=args.label,
    )
    sync_projected_dataset_snapshot(args.projected_datasets_path, args.snapshot_path)
    spec, run_dir = build_run_spec(args)
    run_dir.mkdir(parents=True, exist_ok=True)
    spec_path = run_dir / "manifest.json"
    spec_path.write_text(
        json.dumps(spec, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(f"Snapshot ready at {args.snapshot_path}")
    print(f"Local run manifest: {spec_path}")
    exit_code = launch(spec_path, spec, args)
    if exit_code == 0:
        print(f"Run ID: {spec['run_id']}")
        print(
            "Recover with: "
            "uv run python scripts/recover_modal_run.py "
            f"--run-id {spec['run_id']} --output-root {Path(args.output_root).expanduser().resolve()}"
        )
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
