from __future__ import annotations

import argparse
import os
from pathlib import Path
import subprocess

from modal_cli import modal_cli_prefix
from projected_dataset_snapshot import (
    prepare_snapshot_path,
    sync_projected_dataset_snapshot,
)
from runtime_config import (
    resolve_policyengine_us_path,
    resolve_projected_datasets_path,
)


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_POLICYENGINE_US_PATH = resolve_policyengine_us_path()
DEFAULT_PROJECTED_DATASETS_PATH = resolve_projected_datasets_path()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Snapshot local calibrated H5 datasets and launch the Modal rerun."
    )
    parser.add_argument("--reforms", required=True, help="Comma-separated reform IDs.")
    parser.add_argument(
        "--scoring",
        default="static",
        choices=["static", "dynamic"],
        help="Scoring mode to run on Modal.",
    )
    parser.add_argument(
        "--years",
        required=True,
        help="Year range like 2026-2030 or a comma-separated list.",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output CSV path passed through to modal_batch/compute.py::run_reforms.",
    )
    parser.add_argument(
        "--policyengine-us-path",
        type=Path,
        default=DEFAULT_POLICYENGINE_US_PATH,
        help="Local policyengine-us checkout/worktree to package into Modal.",
    )
    parser.add_argument(
        "--projected-datasets-path",
        type=Path,
        default=DEFAULT_PROJECTED_DATASETS_PATH,
        help="Live projected_datasets directory generated by policyengine-us-data.",
    )
    parser.add_argument(
        "--snapshot-path",
        type=Path,
        default=None,
        help=(
            "Stable snapshot directory copied into the Modal image. If omitted, "
            "a fresh immutable per-run snapshot is created under "
            "projected_datasets_snapshots/."
        ),
    )
    parser.add_argument(
        "--detach",
        action="store_true",
        help="Launch the Modal run in detached mode so it survives client disconnects.",
    )
    parser.add_argument(
        "--modal-target",
        default="run_reforms",
        choices=["run_reforms", "run_cells"],
        help="Which modal_batch/compute.py entrypoint to run.",
    )
    return parser.parse_args()


def effective_modal_target(args: argparse.Namespace) -> str:
    if args.detach and args.modal_target == "run_cells":
        return "run_cells_detached"
    return args.modal_target


def launch_modal(args: argparse.Namespace) -> int:
    env = os.environ.copy()
    env["CRFB_POLICYENGINE_US_PATH"] = str(args.policyengine_us_path)
    env["CRFB_PROJECTED_DATASETS_PATH"] = str(args.snapshot_path)
    env["CRFB_PROJECTED_DATASETS_SNAPSHOT_PATH"] = str(args.snapshot_path)

    command = [*modal_cli_prefix(), "run"]

    if args.detach:
        command.append("--detach")

    modal_target = effective_modal_target(args)
    command.extend(
        [
            str(REPO_ROOT / f"modal_batch/compute.py::{modal_target}"),
            "--reforms",
            args.reforms,
            "--scoring",
            args.scoring,
            "--years",
            args.years,
            "--output",
            args.output,
        ]
    )

    if modal_target != args.modal_target:
        print(
            "Using detached cell submission path; "
            "recover results from the Modal volume after completion."
        )
    print(f"Launching: {' '.join(command)}")
    completed = subprocess.run(command, cwd=REPO_ROOT, env=env)
    return completed.returncode


def main() -> int:
    args = parse_args()
    args.snapshot_path = prepare_snapshot_path(
        args.projected_datasets_path,
        args.snapshot_path,
        repo_root=REPO_ROOT,
        label="modal-refresh",
    )
    for changed in sync_projected_dataset_snapshot(
        args.projected_datasets_path,
        args.snapshot_path,
    ):
        print(f"Snapshotted {changed}")
    print(f"Snapshot ready at {args.snapshot_path}")
    return launch_modal(args)


if __name__ == "__main__":
    raise SystemExit(main())
