# Book settings
title: "Social Security Taxation Reform: Policy Analysis and Impact Assessment"
author: PolicyEngine
logo: policyengine.png
copyright: "2024"

# Force re-execution of notebooks on each build
execute:
  execute_notebooks: cache
  timeout: 600
  allow_errors: false

# Define the left-hand sidebar links
repository:
  url: https://github.com/PolicyEngine/crfb-tob-impacts
  branch: main

# HTML-specific settings
html:
  favicon: policyengine.png
  use_edit_page_button: false
  use_repository_button: true
  use_issues_button: false
  home_page_in_navbar: false
  navbar_number_sections: false
  announcement: ""
  extra_css:
    - _static/custom.css
  extra_extensions:
    - sphinx_external_toc_strict

# Parse and render settings
parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist

# MyST-NB settings for hiding code cells
mystnb:
  execution_mode: cache
  execution_timeout: 600
  execution_allow_errors: false
  execution_excludepatterns: []
  remove_code_source: false
  remove_code_outputs: false
  code_prompt_show: "Show code"
  code_prompt_hide: "Hide code"
  render_plugin: "default"
  render_markdown_format: "commonmark"
  render_image_options:
    width: "100%"
  render_figure_options: {}

# LaTeX settings
latex:
  latex_engine: pdflatex
  use_jupyterbook_latex: true

# Bibliography
bibtex_bibfiles:
  - references.bib

# Sphinx extensions
sphinx:
  extra_extensions:
    - sphinxcontrib.bibtex
  config:
    nb_execution_mode: "force"
    nb_output_stderr: "show"
    nb_render_image_options:
      width: "100%"
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    suppress_warnings: ["mystnb.unknown_mime_type"]
    bibtex_reference_style: author_year
    bibtex_default_style: plain
    html_theme_options:
      repository_url: https://github.com/PolicyEngine/crfb-tob-impacts
      use_repository_button: true
      use_edit_page_button: false
      use_issues_button: false